global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'catalog-service'
    static_configs:
      - targets: ['172.17.0.1:9464']  # use host IP on Linux

  - job_name: 'auth-service'
    static_configs:
      - targets: ['172.17.0.1:9465']
  
  - job_name: 'cart-service'
    static_configs:
      - targets: ['172.17.0.1:9466']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['172.17.0.1:9467']
  
  - job_name: 'payments-service'
    static_configs:
      - targets: ['172.17.0.1:9468']
         