apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-travelersources   # <- automatically injects this namespace

resources:
  - namespace.yaml
  # - api-gateway.yaml
  # - frontend-gateway.yaml
  # - svc-monitor.yaml   ## namespace is monitoring so no!!
  - apps-sealedsecret.yaml
  - mTLs.yaml
  - mTLs-metrics.yaml
  # - prod-cert-tls.yaml
