apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: demo
data:
  PGUSER: appuser
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGDATABASE: mv100db
  PGPORT: "5432"
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_CLIENT_ID: payments-service
  KAFKA_TOPIC_PAYMENTS: mv100db.public.payments
  LOG_LEVEL: info
  PORT: "3005"
  FRONTEND_URL: "https://travelersources.com"
  ORDERS_SERVICE_URL: https://travelersources.com:3003/orders
  SUCCESS_URL: https://travelersources.com/success
  CANCEL_URL: https://travelersources.com/cancel
  OTEL_PROM_PORT: "9468"
