apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

# namespace: dd

resources:
  - cart-local.yaml
  # - auth-sealedsecret.yaml
  # - api-gateway.yaml

# commonLabels:
#   app.kubernetes.io/name: frontend
#   app.kubernetes.io/environment: demo
