apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: demo
data:
  PGUSER: appuser
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGDATABASE: mv100db
  PGPORT: "5432"
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  # KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  # KAFKA_CLIENT_ID: products-service
  # KAFKA_TOPIC_USERS: mv100db.public.products
  LOG_LEVEL: info
  PORT: "3003"
  FRONTEND_URL: "http://frontend.localdev.me"
  OTEL_PROM_PORT: "9466"
