apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-canary
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-stable
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
