apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

# namespace: dd

resources:
  - frontend-local.yaml
  - frontend-sealdsecret.yaml

# commonLabels:
#   app.kubernetes.io/name: frontend
#   app.kubernetes.io/environment: demo
