apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

# namespace: dd

resources:
  - auth-local.yaml
  # - auth-sealedsecret.yaml  ## they sould be cluster deploys
  # - api-gateway.yaml

# commonLabels:
#   app.kubernetes.io/name: frontend
#   app.kubernetes.io/environment: demo
