apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # - api-gateway.yaml
  # - frontend-gateway.yaml
  - svc-monitor.yaml
  - demo-sealedsecret.yaml
  - mTLs.yaml
  - mTLs-metrics.yaml

 