apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: demo
data:
  PGUSER: appuser
  PGDATABASE: mv100db
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGPORT: "5432"
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_CLIENT_ID: auth-service
  KAFKA_TOPIC_USERS: mv100db.public.users
  LOG_LEVEL: info
  PORT: "3002"
  FRONTEND_URL: "http://frontend.localdev.me"
  OTEL_PROM_PORT: "9465"
