apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: demo
data:
  PGUSER: appuser
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGDATABASE: mv100db
  PGPORT: "5432"
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_CLIENT_ID: orders-service
  KAFKA_TOPIC_USERS: mv100db.public.payments
  LOG_LEVEL: info
  PORT: "3005"
  FRONTEND_URL: "http://frontend.localdev.me"
  ORDERS_SERVICE_URL: http://api.localdev.me:3003/orders
  SUCCESS_URL: http://frontend.localdev.me/success
  CANCEL_URL: http://frontend.localdev.me/cancel
  OTEL_PROM_PORT: "9468"
