apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: demo
data:
  PGUSER: appuser
  PGHOST: my-postgresql.postgres.svc.cluster.local
  PGDATABASE: mv100db
  PGPORT: "5432"
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_CLIENT_ID: orders-service
  KAFKA_TOPIC_USERS: mv100db.public.orders
  LOG_LEVEL: info
  PORT: "3004"
  FRONTEND_URL: "https://travelersources.com"
  OTEL_PROM_PORT: "9467"
